name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Pipenv for Github Actions
      uses: VaultVulp/action-pipenv@v1.0.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pipenv shell
        pipenv install
    - name: Lint with flake8
      run: |
        pipenv shell
        pipenv install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pipenv shell
        pipenv install pytest
        pytest
