name: Python Linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --skip-lock
    - name: Lint with flake8
      run: |
        pipenv install flake8 --skip-lock
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Codecov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: 467ba254-5575-4a47-86eb-afaad4eec633

    #- name: Test with pytest
    #  run: |
    #    pipenv install pytest --skip-lock
    #    pipenv run pytest
